### ISSUE TITLE
Does not support running on a machine with AADConnect v1.2.70.0 installed

### ISSUE THREAD

**Issue by KeithwNZ** [Microsoft/AADConnectConfigDocumenter#20] opened 2019-01-17 00:27 UTC
If executed on a computer with AADConnect v1.2.70.0 installed, AzureADConnectSyncDocumenter v1.18.928.0 results in the 9009 error "It seems you may have downloaded the source code instead of a release package. Please download the latest release..."

It does seem to support configuration comparison between AADConnect v1.1.880.0 and v1.2.70.0, but needs to be run on the machine with AADConnect v1.1.880.0 installed.

**Comment by NileshGhodekar** [comment] 2019-01-17 07:47
@KeithwNZ, so do you rerally have the file AzureADConnectSyncDocumenterCmd.exe?  This check was put in the .cmd batch file because some people were downloading the source code (which does not have the compiled executable) instead of the actual release from the link mentioned in the instructions (which does come with the compiled executable).

@M1kep, if you delete the .exe, I expect you to get the same error message.

PS: There is no mention in the instructions that you need to run it on a machine with AADC installed. I use it on my Win10 desktop.

**Comment by KeithwNZ** [comment] 2019-01-18 01:50
Ok - my situation was this: I happened to be running AzureADConnectSyncDocumenterCmd on a server which had AADConnect 1.1.880.0 installed and it worked fine.  I did an in-place upgrade of AADConnect to 1.2.70.0 and then AzureADConnectSyncDocumenterCmd started throwing the error as stated.

**Comment by NileshGhodekar** [comment] 2019-01-18 08:03
Well, if you open AzureADConnectSyncDocumenter-Contoso.cmd in notepad, you'll see that the only reason for this error meesage is if AzureADConnectSyncDocumenterCmd.exe is not found. There is no other check and like I mentioned the AADC connect version upgrade has no bearing on the error you received as AADC is not even required to be installed to use the tool. So another likely cause you are launching the .cmd file from another folder. It will be helpful if you report back what was the cause of this error.

**Comment by NileshGhodekar** [comment] 2019-01-30 11:55
Hi @KeithwNZ ,  I'm closing this as no repro. If you have any additional information on why you got this error, please comment.

**Closed by NileshGhodekar** 2019-01-30 11:55 UTC
